### ISSUE TITLE
TabPage extension not added

### ISSUE THREAD

**Issue by Phentrin** [waldekmastykarz/pnp-starterkit-setup#8]
The TabPage extension is not added in the deployment script 

This extension is present in the Portal.xml template when using Powershell method.

<pnp:CustomAction Name="TabPage" Location="ClientSideExtension.ApplicationCustomizer" ClientSideComponentId="14a8a106-d508-44d0-8fa6-f2f9ed8f571d" Sequence="2" RegistrationType="None" />

It would be great to if it could be added .
thanks
Philippe.

**Comment by waldekmastykarz** [comment]
Thank you for reporting the missing extension. I'll have a look at it asap!

**Comment by waldekmastykarz** [comment]
It turns out that the extension has been removed in favor of links in the hub site navigation. Looking at https://github.com/SharePoint/sp-starter-kit/blob/master/assets/functions/applyportaltemplate/portal.xml you can see that it's not being referenced there anymore. As such, everything is working as expected.

**Comment by Phentrin** [comment]
thanks for the follow up

**Comment by waldekmastykarz** [comment]
Thank you for reaching out. Always good to double check we're not missing anything. Great to see you're using the script 👏
